// src/app/terms/page.tsx
"use client";

import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function TermsPage() {
  return (
    <main className="min-h-screen px-6 py-12">
      <div className="max-w-2xl mx-auto flex flex-col gap-8">
        <Link
          href="/"
          className="flex items-center gap-2 text-[#6B7280] hover:text-[#2D3436] w-fit"
        >
          <ArrowLeft size={18} />
          Back
        </Link>

        <div className="flex flex-col gap-2">
          <h1 className="font-display text-3xl font-bold">Terms &amp; Conditions</h1>
          <p className="text-sm text-[#6B7280]">Last updated: August 2026</p>
        </div>

        <div className="flex flex-col gap-6 text-[#2D3436] leading-relaxed">
          <section className="flex flex-col gap-2">
            <h2 className="font-display font-bold text-lg">1. About Kairo</h2>
            <p className="text-[#6B7280]">
              Kairo is a prototype task-coaching tool built for the IncludAI
              Neurodiversity Hackathon. It helps break tasks into small steps
              and offers encouragement along the way. It is a student project
              and demo, not a finished commercial product.
            </p>
          </section>

          <section className="flex flex-col gap-2">
            <h2 className="font-display font-bold text-lg">2. Not professional advice</h2>
            <p className="text-[#6B7280]">
              Kairo is a productivity and organizational support tool. It is
              not a medical device, and it does not provide medical,
              psychological, therapeutic, or educational diagnosis or
              treatment. It is not a substitute for guidance from a qualified
              doctor, therapist, counselor, or educator. If you have concerns
              about ADHD, attention, or your mental health, please reach out
              to a qualified professional.
            </p>
          </section>

          <section className="flex flex-col gap-2">
            <h2 className="font-display font-bold text-lg">3. AI-generated content</h2>
            <p className="text-[#6B7280]">
              The step-by-step plans and coaching messages you see are
              generated by an AI model. They are meant to be supportive and
              helpful, but they may sometimes be inaccurate, repetitive, or
              not perfectly suited to your situation. Use your own judgment
              when following any suggested step.
            </p>
          </section>

          <section className="flex flex-col gap-2">
            <h2 className="font-display font-bold text-lg">4. Who can use Kairo</h2>
            <p className="text-[#6B7280]">
              Kairo is intended for students and young adults. If you are
              under 13, please use Kairo with the involvement of a parent,
              guardian, or teacher.
            </p>
          </section>

          <section className="flex flex-col gap-2">
            <h2 className="font-display font-bold text-lg">5. No accounts, your device, your data</h2>
            <p className="text-[#6B7280]">
              Kairo does not require you to create an account. Your missions
              and progress are stored locally in your own browser. See our{" "}
              <Link href="/privacy" className="text-[#2F6F5E] underline underline-offset-2">
                Privacy Policy
              </Link>{" "}
              for details on how your task text is processed.
            </p>
          </section>

          <section className="flex flex-col gap-2">
            <h2 className="font-display font-bold text-lg">6. Provided &quot;as is&quot;</h2>
            <p className="text-[#6B7280]">
              As a hackathon prototype, Kairo is provided without warranties
              of any kind, express or implied. To the fullest extent
              permitted by law, the creators of Kairo are not liable for any
              damages or losses arising from your use of the tool.
            </p>
          </section>

          <section className="flex flex-col gap-2">
            <h2 className="font-display font-bold text-lg">7. Changes</h2>
            <p className="text-[#6B7280]">
              These terms may be updated as the project develops. Continued
              use of Kairo after changes means you accept the updated terms.
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}